<a href="https://colab.research.google.com/github/abhash029/Task1portfolio/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Jun  6 11:15:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import numpy as np
import pandas as pd



#creating tensors


In [ ]:
import torch
import numpy as np
import pandas as pd


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
Matrix = torch.tensor([[7,8],
                       [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim


2

In [ ]:
Matrix[0]

tensor([7, 8])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
Tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

### Random Tensors


In [ ]:
#Random Tensors
random_Tensors = torch.rand(3,3)
random_Tensor

NameError: name 'torch' is not defined

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
#create a random tensor
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.5006, 0.0623, 0.0300],
        [0.2856, 0.8196, 0.3377],
        [0.4248, 0.2219, 0.3361]])

In [ ]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.2437, 0.5867, 0.5645, 0.6008, 0.8322, 0.5799, 0.9751, 0.7034,
          0.0271, 0.9543],
         [0.8006, 0.1491, 0.2888, 0.5374, 0.5651, 0.3982, 0.5445, 0.8478,
          0.3706, 0.6912],
         [0.4533, 0.5156, 0.1824, 0.4309, 0.0386, 0.7853, 0.9634, 0.4716,
          0.2646, 0.2115],
         [0.7775, 0.6025, 0.8689, 0.9955, 0.7703, 0.7349, 0.8554, 0.6433,
          0.2206, 0.8828],
         [0.2843, 0.0725, 0.0595, 0.8076, 0.2204, 0.6112, 0.9488, 0.9105,
          0.1452, 0.5598],
         [0.3404, 0.3833, 0.6643, 0.9455, 0.6285, 0.2469, 0.7986, 0.7151,
          0.6532, 0.1887],
         [0.8963, 0.1734, 0.0586, 0.1806, 0.4472, 0.6161, 0.9949, 0.2745,
          0.2217, 0.7189],
         [0.8500, 0.5018, 0.8179, 0.1335, 0.6110, 0.3111, 0.3479, 0.4474,
          0.7267, 0.1861],
         [0.9776, 0.7402, 0.0983, 0.4467, 0.0405, 0.5408, 0.9017, 0.0166,
          0.7958, 0.7141],
         [0.1825, 0.0569, 0.8649, 0.8630, 0.4825, 0.6607, 0.2856, 0.5754,
          0.2765,

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(224 ,224, 3))#height, width, colour channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones


In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.2474, 0.6192, 0.6334],
        [0.7854, 0.9881, 0.2554],
        [0.6560, 0.8470, 0.0568]])

In [ ]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.uint32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.uint32)

In [ ]:
int_32_tensor * float_32_tensor

RuntimeError: Promotion for uint16, uint32, uint64 types is not supported, attempted to promote UInt32 and Float

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6563, 0.8174, 0.0887, 0.0835],
        [0.5588, 0.8473, 0.9748, 0.4665],
        [0.4568, 0.9956, 0.2427, 0.2398]])

In [ ]:
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device tensor is on : {some_tensor.device}")

tensor([[0.6563, 0.8174, 0.0887, 0.0835],
        [0.5588, 0.8473, 0.9748, 0.4665],
        [0.4568, 0.9956, 0.2427, 0.2398]])
datatype of tensor : torch.float32
shape of tensor : torch.Size([3, 4])
device tensor is on : cpu


### Manipulating Tensors

In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply
tensor * 10

tensor([10, 20, 30])

In [ ]:
#subtarct
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#using pytorch builtin
torch.add(tensor,10)


tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.div(tensor,2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
tensor/2

tensor([0.5000, 1.0000, 1.5000])

###Matrix multiplication

In [ ]:
t1 = torch.tensor([[1, 2, 2],
                   [2, 3, 4]])
t1

tensor([[1, 2, 2],
        [2, 3, 4]])

In [ ]:
t2 = torch.tensor([[4, 5, 6],
                   [7, 8, 9],
                   [1,2,3]])
t2

tensor([[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]])

In [ ]:
torch.matmul(t1,t2)

tensor([[20, 25, 30],
        [33, 42, 51]])

In [ ]:
t1.shape
t2.shape

torch.Size([3, 3])

In [ ]:
t1 @ t2

tensor([[20, 25, 30],
        [33, 42, 51]])

In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch_B.Tshape

NameError: name 'torch_B' is not defined

In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
torch.rand(2,3)

tensor([[0.9444, 0.3401, 0.9180],
        [0.3606, 0.1912, 0.3177]])

### tensor aggregation

In [ ]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x)

tensor(91)

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
torch.sum(x)

tensor(460)

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),)

In [ ]:
#stack tensors on top
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x1= torch.vstack([x, x, x, x])
x1

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
z = x.view(1, 9)
z

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
torch.squeeze(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.unsqueeze(x,dim = 0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
y = torch.rand(1,3)
y

tensor([[0.9928, 0.4354, 0.6057]])

In [ ]:
torch.squeeze(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.unsqueeze(x, dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_original = torch.rand(size =(224, 224, 3)) #height widht colour channel
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape : {x_permuted.shape}")#colour channels height width

Previous shape: torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


### Indexing

In [ ]:
a = torch.arange(1,10).reshape(1, 3, 3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
a[0][0]

tensor([1, 2, 3])

In [ ]:
a[0][2][2]

tensor(9)

In [58]:
a[0][1][1]

tensor(5)

In [60]:
a[:, :, 1]

tensor([[2, 5, 8]])

In [1]:
import torch
import numpy as np
import pandas as pd

In [3]:
a = torch.arange(1,10).reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
a[0][1][1]

tensor(5)

In [9]:
a.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
torch.argmin(a)

tensor(0)

In [11]:
torch.argmax(a)

tensor(8)

In [16]:
a.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
a_stacked = torch.stack([a,a,a,a])
a_stacked

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

AttributeError: module 'torch' has no attribute 'view'

In [21]:
x_original = torch.rand(size=(224,224,3))
x_permuted = torch.permute(2,0,1)
pr

TypeError: permute() takes 2 positional arguments but 3 were given

In [23]:
#index on x to return 9
a[:, 2, 2]

tensor([9])

### Pytorch and Numpy

In [24]:
#numpy to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [25]:
array.dtype

dtype('float64')

In [26]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [28]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [29]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### reproducibility

In [30]:
torch.rand(3,3)

tensor([[0.4432, 0.3390, 0.9652],
        [0.6570, 0.4198, 0.0059],
        [0.8929, 0.2333, 0.1620]])

In [31]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1371, 0.9504, 0.5473, 0.8629],
        [0.0111, 0.6628, 0.4596, 0.4070],
        [0.3685, 0.3411, 0.8562, 0.6289]])
tensor([[0.5373, 0.5078, 0.5666, 0.8442],
        [0.3450, 0.8262, 0.8269, 0.5168],
        [0.3099, 0.7530, 0.2747, 0.1213]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [33]:
Random_seed = 42

torch.manual_seed(Random_seed)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Excercises

In [36]:
x1 =  torch.rand(7,7)
x1

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [37]:
x2 = torch.rand(1,7)
x2

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])

In [38]:
torch.matmul(x1, x2.T)

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

In [40]:
Random_seed = 0
torch.manual_seed(Random_seed)
random_tensor_x1 = torch.rand(1,7)
torch.manual_seed(Random_seed)
random_tensor_x2 = torch.rand(7,1)
print(random_tensor_x1)
print(random_tensor_x2)
print(random_tensor_x1 == random_tensor_x2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
tensor([[ True, False, False, False, False, False, False],
        [False,  True, False, False, False, False, False],
        [False, False,  True, False, False, False, False],
        [False, False, False,  True, False, False, False],
        [False, False, False, False,  True, False, False],
        [False, False, False, False, False,  True, False],
        [False, False, False, False, False, False,  True]])


In [42]:
x3 = torch.rand([1,1,1,10])
x3

tensor([[[[0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742, 0.4194,
           0.5529, 0.9527]]]])

In [46]:
x4 = torch.squeeze(x3)
x4

tensor([0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971, 0.8742, 0.4194, 0.5529,
        0.9527])

In [ ]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
